# Generated by Django 3.1.3 on 2021-03-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_pic',
            field=models.ImageField(blank=True, upload_to='img/movies/'),
        ),
        migrations.AlterField(
            model_name='movieuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='img/%Y-%m-%d/'),
        ),
    ]
