# Generated by Django 3.1.3 on 2021-03-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210331_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_pic',
            field=models.ImageField(blank=True, upload_to='photos/movies/'),
        ),
        migrations.AlterField(
            model_name='movieuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='photos/%Y-%m-%d/'),
        ),
    ]
